language: "en-US"
reviews:
  review_details: true
knowledge_base:
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "serpent-vault-b:kr_priv.md"
  mcp:
    usage: enabled
